# Generated by Django 5.2.17 on 2026-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CONVERSATION_ASSIGNED", "Conversation assigned"),
                    ("CONVERSATION_TRANSFERRED", "Conversation transferred"),
                    ("MENTIONED", "Mentioned"),
                    ("CUSTOMER_REPLIED", "Customer replied"),
                    ("SLA_APPROACHING", "SLA approaching"),
                    ("SLA_BREACHED", "SLA breached"),
                    ("ESCALATION_RECEIVED", "Escalation received"),
                    ("AUTOMATION_TRIGGERED", "Automation notification"),
                    ("SUPPORT_MESSAGE", "Support message"),
                ],
                max_length=40,
            ),
        ),
    ]
