# Generated by Django 5.2.17 on 2026-10-06 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_prechatsubmission"),
        ("projects", "0004_projectwidgetconfig"),
        ("queues", "0002_initial"),
        ("teams", "0001_initial"),
        ("visitors", "0002_visitorsession_lifecycle"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="opened_by_side",
            field=models.CharField(
                blank=True,
                choices=[("TENANT", "Tenant"), ("PLATFORM", "Platform")],
                default="",
                db_default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="subject_key",
            field=models.CharField(blank=True, default="", db_default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("type", "PLATFORM_SUPPORT"),
                    models.Q(("subject_key", ""), _negated=True),
                    (
                        "status__in",
                        [
                            "OPEN",
                            "PENDING",
                            "WAITING_FOR_WORKSPACE",
                            "WAITING_FOR_PLATFORM",
                        ],
                    ),
                ),
                fields=("workspace", "subject_key"),
                name="uniq_active_support_thread",
            ),
        ),
    ]
