# Generated by Django 5.2.17 on 2026-10-04 16:38

import projects.domains
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_logo_url_project_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="allowed_domains",
            field=models.TextField(
                blank=True,
                help_text="Hosts allowed to embed the widget, comma-separated: shop.example.com, shop.example.com:8443, *.example.com. Empty = not restricted per project (only the global CORS list applies).",
                validators=[projects.domains.validate_allowed_domains],
            ),
        ),
    ]
