# Generated by Django 5.2.17 on 2026-10-06 06:06

import django.core.validators
import django.db.models.deletion
import integrations.scopes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platforms", "0001_initial"),
        ("projects", "0003_allowed_domains_validation"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9-]{1,62}$",
                                "Lower-case letters, digits and dashes (2-63 chars).",
                            )
                        ],
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(default="host_app", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[integrations.scopes.validate_scopes],
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrations",
                        to="platforms.platform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kid", models.CharField(max_length=64, unique=True)),
                ("public_key_pem", models.TextField()),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[integrations.scopes.validate_scopes],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationTenantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_tenant_id",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._:~-]{0,254}$",
                                "External ids are 1-255 chars of letters, digits and . _ : ~ - (no slashes or spaces).",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("verified_domains", models.JSONField(blank=True, default=list)),
                ("synced_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_mappings",
                        to="integrations.integration",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_mapping",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_mapping",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("integration", "external_tenant_id"),
                        name="uniq_integration_external_tenant",
                    )
                ],
            },
        ),
    ]
