# Generated by Django 5.2.17 on 2026-10-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("platforms", "0001_initial"),
        ("visitors", "0002_visitorsession_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("STAFF", "Staff")],
                        max_length=10,
                    ),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_asserted_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="integrations.integration",
                    ),
                ),
                (
                    "tenant_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="integrations.integrationtenantmapping",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identity",
                        to="visitors.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_role", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="integrations.externalidentity",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_memberships",
                        to="platforms.platform",
                    ),
                ),
                (
                    "tenant_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_memberships",
                        to="integrations.integrationtenantmapping",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "CUSTOMER")),
                fields=("integration", "tenant_mapping", "external_user_id"),
                name="uniq_ext_customer_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "STAFF")),
                fields=("integration", "external_user_id"),
                name="uniq_ext_staff_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "CUSTOMER"),
                        ("tenant_mapping__isnull", False),
                        ("visitor__isnull", False),
                    ),
                    models.Q(
                        ("kind", "STAFF"),
                        ("tenant_mapping__isnull", True),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ext_identity_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant_mapping__isnull", False)),
                fields=("identity", "tenant_mapping"),
                name="uniq_ext_membership_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform__isnull", False)),
                fields=("identity", "platform"),
                name="uniq_ext_membership_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("platform__isnull", True), ("tenant_mapping__isnull", False)
                    ),
                    models.Q(
                        ("platform__isnull", False), ("tenant_mapping__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="ext_membership_exactly_one_scope",
            ),
        ),
    ]
